### ISSUE TITLE
Pronunciation

### ISSUE THREAD

**Issue by qistoph** [LeakIX/DocSite#2]
It might be too futile or obvious for others, but I keep wondering if it's "Leak 9" (/lēk/ /nīn/) or "Leak I X" (/lēk/ /ī/ /ĕks/).

Maybe a hint about pronunciation could be added here:

https://github.com/LeakIX/DocSite/blob/ef4eebe91db1dcd46523a210c64c2dee3862ee37/content/docs/getting-started.md?plain=1#L11

```
LeakIX (/lēk ī ĕks/) is the first platform combining [...]
```

**Comment by dannywillems** [comment]
Ah, you are not the first one! It's Leak I X :). We'll add. Thanks for the suggestion!

**Comment by dannywillems** [comment]
Updated.
